# Generated by Django 3.1.5 on 2021-01-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210118_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.TextField(choices=[('EDTR', '에디터'), ('MNGR', '매니저'), ('MSTR', '경영진'), ('MKTR', '마케터'), ('DS', '디자이너'), ('SLS', '영업자')], default='EDTR', max_length=4),
        ),
    ]
