# Generated by Django 3.1.5 on 2021-01-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll',
            new_name='role',
        ),
    ]
