# Generated by Django 3.1.5 on 2021-01-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210130_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='tags',
        ),
    ]
